In [3]:
import pandas as pd

In [4]:
main_data = pd.read_excel(r"C:\Users\hp\OneDrive\Documents\Documents\Datasets\Medical claims and denial Data\CA Hospital Dataset – Q1 2025\Data eda\Cleaned Data\Final_Merged_data.xlsx")
main_data.head(10)

,Billing_Id,Patient_Id,Encounter_Id,Insurance_Provider,Claim_Id,Claim_Billing_Date,Billed_Amount,Paid_Amount,Claim_Status,Denial_Reason,...,State,Registration_Date,Denial_Id,Denial_Reason_Code,Denied_Amount,Denial_Date,Appeal_Filed,Appeal_Status,Appeal_Resolution_Date,Final_Outcome
0,BILL000001,PAT001464,ENC000001,BCBS,CLM000001,2025-02-06,1971.5,0.0,Denied,Claim Billed to Wrong Payer,...,CA,2025-01-19,DEN00001,CO119,1971.52,2025-03-01,Yes,Approved,2025-03-10,Paid
1,BILL000002,PAT025832,ENC000002,Medicare,CLM000002,2025-05-01,1243.8,736.1,Paid,NaN,...,CA,2025-03-30,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
2,BILL000003,PAT055873,ENC000003,BCBS,CLM000003,2025-02-23,4854.1,2676.1,Paid,NaN,...,WA,2025-01-18,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
3,BILL000004,PAT048558,ENC000004,BCBS,CLM000004,2025-04-20,2638.2,1861.4,Paid,NaN,...,CA,2025-03-21,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
4,BILL000006,PAT050873,ENC000006,BCBS,CLM000005,2025-02-06,2571.1,1924.4,Paid,NaN,...,CA,2025-01-05,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
5,BILL000007,PAT041889,ENC000007,Cigna,CLM000006,2025-02-26,1425.3,1115.4,Paid,NaN,...,CA,2025-02-10,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
6,BILL000008,PAT042329,ENC000008,UHC,CLM000007,2025-02-12,943.8,593.0,Paid,NaN,...,CA,2025-01-14,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
7,BILL000009,PAT042934,ENC000009,Humana,CLM000008,2025-03-14,952.2,572.1,Paid,NaN,...,CA,2025-02-15,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
8,BILL008323,PAT009159,ENC008323,Medicaid,CLM007128,2025-01-31,999.2,0.0,Denied,Out-of-Network Provider,...,CA,2025-01-13,DEN08323,PR109,999.19,2025-02-20,No,NaN,NaT,NaN
9,BILL000011,PAT053469,ENC000011,Aetna,CLM000010,2025-04-16,348.4,235.1,Paid,NaN,...,CA,2025-03-13,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN

In [5]:
main_data.isnull().sum()

Billing_Id                    0
Patient_Id                    0
Encounter_Id                  0
Insurance_Provider            0
Claim_Id                      0
Claim_Billing_Date            0
Billed_Amount                 0
Paid_Amount                   0
Claim_Status                  0
Denial_Reason             53640
Provider_Id                   0
Visit_Date                    0
Visit_Type                    0
Department                    0
Reason_For_Visit              0
Diagnosis_Code                0
Admission_Type            41279
Discharge_Date            38893
Length_Of_Stay            38893
Status                        0
Readmitted_Flag               0
Patient_Name                  0
Dob                           0
Gender                        0
Ethnicity                     0
Marital_Status                0
City                       5900
State                      5900
Registration_Date             0
Denial_Id                 53640
Denial_Reason_Code        53640
Denied_Amount             53640
Denial_Date               53640
Appeal_Filed              53640
Appeal_Status             54242
Appeal_Resolution_Date    54242
Final_Outcome             54242
dtype: int64

In [6]:
# Handling missing Denied_Amount and Denial_Reason.
main_data["Denied_Amount"] = pd.Series(main_data["Denied_Amount"]).fillna(0)
main_data["Denial_Reason"] = pd.Series(main_data["Denial_Reason"]).fillna("No Denial")

# Creating Denial flags upon Claim_Status and Final_Outcome.

In [7]:
main_data.columns

Index(['Billing_Id', 'Patient_Id', 'Encounter_Id', 'Insurance_Provider',
       'Claim_Id', 'Claim_Billing_Date', 'Billed_Amount', 'Paid_Amount',
       'Claim_Status', 'Denial_Reason', 'Provider_Id', 'Visit_Date',
       'Visit_Type', 'Department', 'Reason_For_Visit', 'Diagnosis_Code',
       'Admission_Type', 'Discharge_Date', 'Length_Of_Stay', 'Status',
       'Readmitted_Flag', 'Patient_Name', 'Dob', 'Gender', 'Ethnicity',
       'Marital_Status', 'City', 'State', 'Registration_Date', 'Denial_Id',
       'Denial_Reason_Code', 'Denied_Amount', 'Denial_Date', 'Appeal_Filed',
       'Appeal_Status', 'Appeal_Resolution_Date', 'Final_Outcome'],
      dtype='object')

In [11]:
main_data["Claims_Status_Flag"] = main_data['Claim_Status'].apply(lambda x: 1 if x=="Denied" else 0)
# Filling nan values in Final_Outcome as paid for claims which are approved to create data consistency and calculating correct denial rate
main_data["Final_Outcome"] = main_data["Final_Outcome"].fillna("Paid")
main_data["Final_Status_Flag"] = main_data["Final_Outcome"].apply(lambda x: 1 if x== "Written off" else 0 if x=='Paid' else 2 )

In [9]:
main_data["Final_Outcome"].isnull().sum()

np.int64(54242)

In [12]:
print(main_data["Final_Outcome"].isnull().sum())
print(main_data["Final_Outcome"].head(10))
print(main_data["Final_Status_Flag"].head(10))

0
0    Paid
1    Paid
2    Paid
3    Paid
4    Paid
5    Paid
6    Paid
7    Paid
8    Paid
9    Paid
Name: Final_Outcome, dtype: object
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Final_Status_Flag, dtype: int64

# Saving this file and then reading it back to perform further operations

In [14]:
# Saving File
main_data.to_excel(r"C:\Users\hp\OneDrive\Documents\Documents\Datasets\Medical claims and denial Data\CA Hospital Dataset – Q1 2025\Data eda\Cleaned Data\Final_Merged_data.xlsx", index= False)

In [5]:
# Reading the file
main_data = pd.read_excel(r"C:\Users\hp\OneDrive\Documents\Documents\Datasets\Medical claims and denial Data\CA Hospital Dataset – Q1 2025\Data eda\Cleaned Data\Final_Merged_data.xlsx")

In [6]:
main_data.head()

,Billing_Id,Patient_Id,Encounter_Id,Insurance_Provider,Claim_Id,Claim_Billing_Date,Billed_Amount,Paid_Amount,Claim_Status,Denial_Reason,...,Denial_Id,Denial_Reason_Code,Denied_Amount,Denial_Date,Appeal_Filed,Appeal_Status,Appeal_Resolution_Date,Final_Outcome,Claims_Status_Flag,Final_Status_Flag
0,BILL000001,PAT001464,ENC000001,BCBS,CLM000001,2025-02-06,1971.5,0.0,Denied,Claim Billed to Wrong Payer,...,DEN00001,CO119,1971.52,2025-03-01,Yes,Approved,2025-03-10,Paid,1,0
1,BILL000002,PAT025832,ENC000002,Medicare,CLM000002,2025-05-01,1243.8,736.1,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
2,BILL000003,PAT055873,ENC000003,BCBS,CLM000003,2025-02-23,4854.1,2676.1,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
3,BILL000004,PAT048558,ENC000004,BCBS,CLM000004,2025-04-20,2638.2,1861.4,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
4,BILL000006,PAT050873,ENC000006,BCBS,CLM000005,2025-02-06,2571.1,1924.4,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0

# Creating KPI metrics

In [30]:
# Since the final_outcome had three categories, I defined a binary flag where only written-off claims were treated as 1, representing actual revenue loss. Paid and reprocessed claims are considered recoverable, therefore decided to mark them a 0. This is to allow for clearer financial impact. Inorder to do so i am restructing my main_data.

In [31]:
main_data.drop(columns=["Final_Status_Flag"], inplace=True)
main_data["Final_Status_Flag"] = main_data["Final_Outcome"].apply(lambda x: 1 if x== "Written off" else 0 )

In [34]:
main_data["Final_Status_Flag"].unique()

array([0, 1])

In [35]:
# Saving the file and reading it again.
main_data.to_excel(r"C:\Users\hp\OneDrive\Documents\Documents\Datasets\Medical claims and denial Data\CA Hospital Dataset – Q1 2025\Data eda\Cleaned Data\Final_Merged_data.xlsx", index= False)

In [4]:
# Reading the file
main_data = pd.read_excel(r"C:\Users\hp\OneDrive\Documents\Documents\Datasets\Medical claims and denial Data\CA Hospital Dataset – Q1 2025\Data eda\Cleaned Data\Final_Merged_data.xlsx")
main_data.head(10)

,Billing_Id,Patient_Id,Encounter_Id,Insurance_Provider,Claim_Id,Claim_Billing_Date,Billed_Amount,Paid_Amount,Claim_Status,Denial_Reason,...,Denial_Id,Denial_Reason_Code,Denied_Amount,Denial_Date,Appeal_Filed,Appeal_Status,Appeal_Resolution_Date,Final_Outcome,Claims_Status_Flag,Final_Status_Flag
0,BILL000001,PAT001464,ENC000001,BCBS,CLM000001,2025-02-06,1971.5,0.0,Denied,Claim Billed to Wrong Payer,...,DEN00001,CO119,1971.52,2025-03-01,Yes,Approved,2025-03-10,Paid,1,0
1,BILL000002,PAT025832,ENC000002,Medicare,CLM000002,2025-05-01,1243.8,736.1,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
2,BILL000003,PAT055873,ENC000003,BCBS,CLM000003,2025-02-23,4854.1,2676.1,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
3,BILL000004,PAT048558,ENC000004,BCBS,CLM000004,2025-04-20,2638.2,1861.4,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
4,BILL000006,PAT050873,ENC000006,BCBS,CLM000005,2025-02-06,2571.1,1924.4,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
5,BILL000007,PAT041889,ENC000007,Cigna,CLM000006,2025-02-26,1425.3,1115.4,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
6,BILL000008,PAT042329,ENC000008,UHC,CLM000007,2025-02-12,943.8,593.0,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
7,BILL000009,PAT042934,ENC000009,Humana,CLM000008,2025-03-14,952.2,572.1,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0
8,BILL008323,PAT009159,ENC008323,Medicaid,CLM007128,2025-01-31,999.2,0.0,Denied,Out-of-Network Provider,...,DEN08323,PR109,999.19,2025-02-20,No,NaN,NaT,Paid,1,0
9,BILL000011,PAT053469,ENC000011,Aetna,CLM000010,2025-04-16,348.4,235.1,Paid,No Denial,...,NaN,NaN,0.00,NaT,NaN,NaN,NaT,Paid,0,0

In [5]:
kpi = {}
kpi["Total_Claims"] = main_data["Claim_Id"].nunique()
kpi["Total_Billed_Amount"] = main_data ["Billed_Amount"].sum()
kpi["Total_Paid_Amount"] = round(main_data["Paid_Amount"].sum(),2)
kpi["Written_Off"] = main_data[main_data["Final_Outcome"] == "Written off"]["Denied_Amount"].sum()
kpi["Initial_Denial"] = round(main_data["Claims_Status_Flag"].mean()*100,2)
kpi["Final_Revenue_Loss"] = round(main_data["Final_Status_Flag"].mean()*100,2)
kpi["Appeal_Approval_Rate"] = round(((kpi["Initial_Denial"] - kpi["Final_Revenue_Loss"])/kpi["Initial_Denial"])*100,2)

In [6]:
for key, values in kpi.items():
    print(key, values)

Total_Claims 59638
Total_Billed_Amount 96403608.6
Total_Paid_Amount 56348581.9
Written_Off 873241.19
Initial_Denial 10.06
Final_Revenue_Loss 0.91
Appeal_Approval_Rate 90.95

In [11]:
# Saving the KPI dictionary into xlsx format.
KPI_info = pd.DataFrame(list(kpi.items()),columns=["KPI", "values"])

In [13]:
file_path = r"C:\Users\hp\OneDrive\Documents\Documents\Datasets\Medical claims and denial Data\CA Hospital Dataset – Q1 2025\Data eda\Cleaned Data\Final_Merged_data.xlsx"
with pd.ExcelWriter(file_path, mode="a") as writer: KPI_info.to_excel(writer, sheet_name="KPI", index=False)